version: "3.7"
services:
  nats:
    image: nats:2.6.4
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command: --jetstream -m 8222 --store_dir /tmp/nats

#        JetStream Options:
#          -js, --jetstream                 Enable JetStream functionality.
#          -sd, --store_dir <dir>           Set the storage directory.

#Cluster Options:
#  --routes <rurl-1, rurl-2>    Routes to solicit and connect
#  --cluster <cluster-url>      Cluster URL for solicited routes
#  --cluster_name <string>      Cluster Name, if not set one will be dynamically generated
#  --no_advertise <bool>        Do not advertise known cluster information to clients
#  --cluster_advertise <string> Cluster URL to advertise to other servers
#  --connect_retries <number>   For implicit routes, number of connect retries    